version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${APP_PORT:-8001}:8001"
    volumes:
      - ./db_data:/app/data
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
